#%RAML 1.0 NamedExample
[
  {
    "employeeId" : 1,
    "firstName": "Rishav",
    "lastName": "Dutta",
    "phone": "7980710289",
    "email": "rishav@gmail.com",
    "deliveryAddress": "Baruipur, Ukilpara",
    "postalCode": 700144
  },
  {
    "employeeId" : 2,
    "firstName": "Riju",
    "lastName": "Das",
    "phone": "8045210289",
    "email": "riju@gmail.com",
    "deliveryAddress": "Rajpur",
    "postalCode": 700108
  }
]
