#%RAML 1.0 NamedExample
 {
    "employeeId" : 1,
    "firstName": "Rishav",
    "lastName": "Dutta",
    "phone": "7980710289",
    "email": "rishav@gmail.com",
    "deliveryAddress": "Baruipur, Ukilpara",
    "postalCode": 700144
 }