#%RAML 1.0 NamedExample
  {
    "firstName": "Rahul",
    "lastName": "Dutta",
    "phone": "7980710289",
    "email": "rahul@gmail.com",
    "deliveryAddress": "Jadavpur",
    "postalCode": 700144
  }